---
title       : CAPM
subtitle    : Capital Asset Pricing Model
author      : Savir Huitron
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [mathjax, highcharts]            # {mathjax, quiz, bootstrap}
ext_widgets : {rCharts: [libraries/highcharts]}
mode        : selfcontained
knit        : slidify::knit2slides
github: 
    user: savirhuitron
    repo: capm1
---

## Capital Asset Pricing Model

The Capital Asset Pricing Model is a model that describes the relationship between **risk** and **expected return** and that is used in the pricing of risky securities. [investopedia](http://www.investopedia.com/terms/c/capm.asp)

The model takes into account the asset's sensitivity to non-diversifiable risk (also known as systematic risk or market risk), often represented by the quantity **beta** (**$\beta$**)  in the financial industry, as well as the expected return of the market and the expected return of a theoretical risk-free asset. 


## The Model

The formula for the model was introduced by **Jack Traynor**, **William F. Sharpe**, **John Lintner** and **Jan Mossin** independently, building on the earlier work of **Harry Markowitz** on diversification and modern portfolio theory. Sharpe, Markowitz and Merton Miller jointly received the 1990 Nobel Memorial Prize in Economics for this contribution to the field of financial economics. [wikipedia](https://en.wikipedia.org/wiki/Capital_asset_pricing_model)


--- .class #id 

## The Model

The model is the next: 

$$E(R_i) = R_f + \beta_i  (E(R_m)- R_f)$$

Where: 

$E(R_i) =$ *Is the expected return on the capital asset*

$R_f =$ *Is the risk-free rate of interest*

$\beta_i =$ *Is the beta of the capital asset, which is in our linear model* $\hat{\beta_i} = Cor(Y,X) \frac{Sd(Y)}{Sd(X)}$

$R_m =$ *Is the expected return of the market*


--- 

## The Interpretation

* CAPM helps investors calculate risk and what type of return they should expect on their investment. 

* In our model, the $\beta_i$ it's a measure of the volatility, or systematic risk, of a security or a portfolio in comparision to the market as a whole, in this case we are using the [IPC](http://www.bmv.com.mx/en/indices/main/) as the whole market,  and its [components](http://www.bmv.com.mx/en/markets/special-information). 

* Beta is calculated using regression analysis, and you can think of beta as the tendency of a security's returns to respond to swings in the market. a beta of 1 indicates that the security's price will move with the market. A beta of less than 1 means that the security will be less volatile than the market. A beta greater than 1 indicates that the security's price will be less volatile than the market. For example, if a stock's __beta__ is 1.2, it's theoretically 20% more volatile than the market. [investopedia](http://www.investopedia.com/terms/b/beta.asp?utm_term=beta&utm_content=sem-unp&utm_medium=organic&utm_source=&utm_campaign=&ad=&an=&am=&o=40186&askid=&l=dir&qsrc=999&qo=investopediaSiteSearch)


---

## CAPM 

This shows in the "x axis" the nivels of the Beta, the size of the bubble it's the expected return on the capital asset.

```{r echo = F, results = 'asis'}

b6 <- read.csv("capm_beta.csv")

n2 <- hPlot(EMISORA ~ BETA , data = b6, type = "bubble", size = "CAPM", group = "NIVELES", 
    title = "BETAS of the Components of IPC Index")
    n2$chart(width = 1200, height = 350)
    n2$addParams(dom = "myChart")
    n2$chart(zoomType = "xy")
    n2$exporting(enabled = T)
    n2$print("myChart")

```

